### ISSUE TITLE
Avatar editor issue

### ISSUE THREAD

**Issue by molnosikristof** [purposeindustries/intellyo-application-design-system#284]
If I am using the "Upload picture" button to upload an avatar on the "/avatars" site, the same pic appears for the "Upload logo" button.
![screen shot 2018-02-07 at 14 16 35](https://user-images.githubusercontent.com/7290118/35918300-95c25cbc-0c11-11e8-9be1-ea4c9d7db141.png)

**Comment by ruffle1986** [comment]
@molnosikristof I'm sorry but I can't reproduce it. :(

Can you please take a look again and send a video or something like this?

**Comment by molnosikristof** [comment]
Ohh, sorry, I've already fixed it.
